In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../input/train.csv")

data.head()

battery_power  blue     ...       wifi  price_range
0            842     0     ...          1            1
1           1021     1     ...          0            2
2            563     1     ...          0            2
3            615     1     ...          0            2
4           1821     1     ...          0            1

[5 rows x 21 columns]

In [3]:
data['price_range'].value_counts()

3    500
2    500
1    500
0    500
Name: price_range, dtype: int64

In [4]:
list(data)

['battery_power',
 'blue',
 'clock_speed',
 'dual_sim',
 'fc',
 'four_g',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'n_cores',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'three_g',
 'touch_screen',
 'wifi',
 'price_range']

In [5]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
x = ss.fit_transform(x)

x

NameError: name 'x' is not defined

In [6]:
x = data[['battery_power',
 'blue',
 'clock_speed',
 'dual_sim',
 'fc',
 'four_g',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'n_cores',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'three_g',
 'touch_screen',
 'wifi']]

y=data['price_range']

In [7]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Decision Tree

In [8]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
a = clf.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix

print(accuracy_score(y_test,a))
print(confusion_matrix(y_test,a))

0.83
[[87 12  0  0]
 [12 79  9  0]
 [ 0 10 83 12]
 [ 0  0 13 83]]


# Random Forest

In [10]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(x_train,y_train)
a = clf.predict(x_test)

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [11]:
print(accuracy_score(a,y_test))
print(confusion_matrix(a,y_test))

0.825
[[92 10  0  0]
 [ 7 81 15  1]
 [ 0  9 78 16]
 [ 0  0 12 79]]


# Plotting

In [12]:
import seaborn as sns

list(data)

['battery_power',
 'blue',
 'clock_speed',
 'dual_sim',
 'fc',
 'four_g',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'n_cores',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'three_g',
 'touch_screen',
 'wifi',
 'price_range']

# SVM

In [13]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

clf = SVC(kernel='linear')
scores = cross_val_score(clf,x,y, cv=5)
scores.mean()


0.9730000000000001

In [14]:
print(accuracy_score(y_test,a))
print(confusion_matrix(y_test,a))

0.825
[[92  7  0  0]
 [10 81  9  0]
 [ 0 15 78 12]
 [ 0  1 16 79]]


In [15]:
from sklearn.svm import SVC
clf = SVC(kernel='rbf')
clf.fit(x_train,y_train)
a = clf.predict(x_test)

print(accuracy_score(y_test,a))
print(confusion_matrix(y_test,a))

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.24
[[  0   0   0  99]
 [  0   0   0 100]
 [  0   0   0 105]
 [  0   0   0  96]]


# KNN

In [16]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=10)
clf.fit(x_train,y_train)
a = clf.predict(x_test)

print(accuracy_score(y_test,a))
print(confusion_matrix(y_test,a))

0.9275
[[97  2  0  0]
 [ 4 93  3  0]
 [ 0  9 92  4]
 [ 0  0  7 89]]
